
module.exports = {    
    CAT_ARTICULO:'CAT_ARTICULO',
    CAT_ARTICULO_SUCURSAL:'CAT_ARTICULO_SUCURSAL',
    VE_VENTA:'VE_VENTA',
    VE_VENTA_DETALLE:'VE_VENTA_DETALLE',
    VE_MOVIMIENTO:'VE_MOVIMIENTO',
}